# colorscheme
include kanagawa.conf

# font
font_family IosevkaTerm NF
bold_font auto
italic_font auto
bold_italic_font auto

font_size 16.0

modify_font underline_position 3
modify_font underline_thickness 50%

disable_ligatures always

# cursor
cursor_shape beam
cursor_beam_thickness 1.5
cursor_blink_interval 0

# layout
enabled_layouts grid

# window
map alt+enter new_window
map alt+] next_window
map alt+[ prev_window

# tab
map alt+t new_tab
map alt+n next_tab
map alt+p prev_tab
