[core]

plugins = \
    decoration \
    autostart \
    command \
    grid \
    expo \
    move \
    resize \
    switcher \
    input-method-v1 \

# close focus window
close_top_view = <super> KEY_Q

# workspace arranged into a grid: 2 x 2
vwidth = 2
vheight = 2

[output:eDP-1]
mode = 2240x1400@60000
position = 0,0
transform = normal
scale = 1.000000

[autostart]
#Gtk+3 applications slow startup or .desktop files not opening
#https://github.com/WayfireWM/wayfire/wiki/Tips-&-Tricks#gtk3-applications-slow-startup-or-desktop-files-not-opening
0_env = dbus-update-activation-environment --systemd WAYLAND_DISPLAY DISPLAY XAUTHORITY

background = swaybg -i $HOME/.config/wallpaper.jpg -m fill

inputmethod = fcitx5

statusbar = waybar

[command]

# terminal
binding_terminal = <super> KEY_ENTER
command_terminal = kitty

# launcher
binding_launcher = <super> KEY_P
command_launcher = fuzzel

# volume controls
# https://alsa-project.org
repeatable_binding_volume_up = KEY_VOLUMEUP
command_volume_up = amixer set Master 5%+
repeatable_binding_volume_down = KEY_VOLUMEDOWN
command_volume_down = amixer set Master 5%-
binding_mute = KEY_MUTE
command_mute = amixer set Master toggle

[decoration]
title_height = 0
border_size = 1

[grid]
# ⇱ ↑ ⇲   │ 7 8 9
# ← f →   │ 4 5 6
# ⇱ ↓ ⇲ d │ 1 2 3 0
restore = <super> KEY_0
slot_bl = <super> KEY_1
slot_b  = <super> KEY_2 | <super> KEY_J
slot_br = <super> KEY_3
slot_l  = <super> KEY_4 | <super> KEY_H
slot_c  = <super> KEY_5 | <super> KEY_SPACE
slot_r  = <super> KEY_6 | <super> KEY_L
slot_tl = <super> KEY_7
slot_t  = <super> KEY_8 | <super> KEY_K
slot_tr = <super> KEY_9

[switcher]
next_view = <alt> KEY_TAB

[expo]
toggle = <super>

[move]
activate = <super> BTN_LEFT

[resize]
activate = <super> BTN_RIGHT
